[package]
name = "aoc"
edition = "2021"

[dependencies]
anyhow = "=1.0.95"
clap = { version = "=4.5.24", features = ["derive"] }
clap-verbosity-flag = "=3.0.2"
itertools = "=0.14.0"
lazy_static = "=1.5.0"
log = { version = "=0.4.22", features = ["release_max_level_warn"] }
simple_logger = "=5.0.0"
