[package]
name = "aoc"
edition = "2024"

[dependencies]
anyhow = "=1.0.98"
clap = { version = "=4.5.37", features = ["derive"] }
clap-verbosity-flag = "=3.0.2"
itertools = "=0.14.0"
log = { version = "=0.4.27", features = ["release_max_level_warn"] }
simple_logger = "=5.0.0"
