[tasks.check]
depends = [
    "check:rustfmt",
    "check:prettier",
    "check:renovateconfig"
]

[tasks."check:rustfmt"]
run = "cargo fmt --check"

[tasks."check:prettier"]
run = "prettier --check ."

[tasks."check:renovateconfig"]
run = "renovate-config-validator --strict"
tools."npm:renovate" = "latest"

[tasks.fix]
depends = [
    "fix:prettier",
    "fix:rustfmt"
]

[tasks."fix:rustfmt"]
run = "cargo fmt"

[tasks."fix:prettier"]
run = "prettier --write --cache-location .prettiercache ."

[tools]
node = "22"
"npm:prettier" = "3.6.2"
rust = { version = "1.88.0", components = "clippy,rustfmt" }
