name: Build, test and run
on:
  pull_request:
    paths:
      - "**.rs"
      - ".github/workflows/build-test-run.yaml"
      - "Cargo.lock"
      - "Cargo.toml"
  workflow_call:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-run:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        profile:
          - dev
          - release
          - test
        include:
          - clippy: false
          - run: true
          - test: false
          - profile: dev
            clippy: true
          - profile: test
            run: false
            test: true

    name: ${{matrix.runner}} - ${{matrix.profile}} - Build + test + run
    runs-on: ${{matrix.runner}}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Fetch dependencies
        run: cargo fetch --verbose --locked
      - name: Build
        run: cargo build --verbose --frozen --all-targets --profile ${{matrix.profile}}
      - if: ${{ matrix.test }}
        name: Test
        run: cargo test --verbose --frozen --all-targets --profile ${{matrix.profile}}
      - name: Check
        run: cargo check --verbose --frozen --all-targets --profile ${{matrix.profile}}
      - if: ${{ matrix.clippy }}
        name: Clippy
        run: >
          cargo clippy --verbose --frozen --all-targets --profile ${{matrix.profile}} --
          -D warnings
          -D clippy::complexity
          -D clippy::correctness
          -D clippy::pedantic
          -D clippy::perf
          -D clippy::style
          -D clippy::suspicious
      - if: ${{ matrix.run }}
        name: Run subcommand all
        run: cargo run --verbose --frozen --profile ${{matrix.profile}} -- -vv all
