name: Build, test and run
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build-test-run:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        profile:
          - dev
          - release
          - test
        include:
          - clippy: false
          - run: true
          - test: false
          - profile: dev
            clippy: true
          - profile: test
            run: false
            test: true

    name: ${{matrix.runner}} - ${{matrix.profile}} - Build + test + run
    runs-on: ${{matrix.runner}}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup tools through mise
        uses: nikobockerman/github-actions/.github/actions/mise-project-setup@f3187da9f481f613db86e254b6537973176cdab1
      - name: Setup rust cache
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          key: ${{ matrix.profile }}
      - name: Fetch dependencies
        run: cargo fetch --verbose --locked
      - name: Build
        run: cargo build --verbose --frozen --all-targets --profile ${{matrix.profile}}
      - if: ${{ matrix.test }}
        name: Test
        run: cargo test --verbose --frozen --all-targets --profile ${{matrix.profile}}
      - name: Check
        run: cargo check --verbose --frozen --all-targets --profile ${{matrix.profile}}
      - if: ${{ matrix.clippy }}
        name: Clippy
        run: cargo clippy --verbose --frozen --all-targets --profile ${{matrix.profile}} -- -D warnings
      - if: ${{ matrix.run }}
        name: Run subcommand all
        env:
          RUST_BACKTRACE: 1
        run: cargo run --verbose --frozen --profile ${{matrix.profile}} -- -vvvv all
