name: Check - Devcontainer
on:
  pull_request:
    paths:
      - "**.rs"
      - ".devcontainer/**"
      - ".github/workflows/check-devcontainer.yaml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "rust-toolchain.toml"
      - "src/**/input-*.txt"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-devcontainer.yaml@065515a366665df781d8c7939c05dee79a30d31e
    with:
      runCmd: cargo run --verbose --locked --profile dev -- -vvvv all
