name: Check - Devcontainer
on:
  pull_request:
    paths:
      - "**.rs"
      - ".devcontainer/**"
      - ".github/workflows/check-devcontainer.yaml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "rust-toolchain.toml"
      - "src/**/input-*.txt"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-devcontainer.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
    with:
      runCmd: cargo run --verbose --locked --profile dev -- -vvvv all
