name: Check - rustfmt
on:
  pull_request:
    paths:
      - "**.rs"
      - ".github/workflows/check-rustfmt.yaml"
      - "Cargo.toml"
  workflow_call:
  workflow_dispatch:

jobs:
  check-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup rust tools
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: rustfmt
        run: cargo fmt --check
