name: Check - Devcontainer
on:
  pull_request:
    paths:
      - "**.rs"
      - ".devcontainer/**"
      - ".github/workflows/check-devcontainer.yaml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "rust-toolchain.toml"
      - "src/**/input-*.txt"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-devcontainer.yaml@a3ff11ed76f5e286d3a5e11ec6f6395ddbe6412d
    with:
      runCmd: cargo run --verbose --locked --profile dev -- -vvvv all
