name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-test-run:
    uses: ./.github/workflows/build-test-run.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  check-rustfmt:
    uses: ./.github/workflows/check-rustfmt.yaml
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
