name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  mise-cache-ubuntu:
    uses: nikobockerman/github-workflows/.github/workflows/mise-prepare-cache.yaml@bb97c7b995d030798ca719dfe898756878f239ce # v1.0.2
    with:
      runner: ubuntu-latest
  mise-cache-macos:
    uses: nikobockerman/github-workflows/.github/workflows/mise-prepare-cache.yaml@bb97c7b995d030798ca719dfe898756878f239ce # v1.0.2
    with:
      runner: macos-latest
  mise-cache-windows:
    uses: nikobockerman/github-workflows/.github/workflows/mise-prepare-cache.yaml@bb97c7b995d030798ca719dfe898756878f239ce # v1.0.2
    with:
      runner: windows-latest
  build-test-run:
    needs:
      - mise-cache-ubuntu
      - mise-cache-macos
      - mise-cache-windows
    uses: ./.github/workflows/build-test-run.yaml
  check-prettier:
    needs: mise-cache-ubuntu
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@bb97c7b995d030798ca719dfe898756878f239ce # v1.0.2
    with:
      task: check:prettier
  check-renovate-config:
    needs: mise-cache-ubuntu
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@bb97c7b995d030798ca719dfe898756878f239ce # v1.0.2
    with:
      task: check:renovateconfig
  check-rustfmt:
    needs: mise-cache-ubuntu
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@bb97c7b995d030798ca719dfe898756878f239ce # v1.0.2
    with:
      task: check:rustfmt

  check:
    needs:
      - build-test-run
      - check-prettier
      - check-renovate-config
      - check-rustfmt
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
