name: CI
on:
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-test-run:
    uses: ./.github/workflows/build-test-run.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@227dcb13eb6b8e20859b6561ddd38632047b12bd
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@227dcb13eb6b8e20859b6561ddd38632047b12bd
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@227dcb13eb6b8e20859b6561ddd38632047b12bd
  check-rustfmt:
    uses: ./.github/workflows/check-rustfmt.yaml
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@227dcb13eb6b8e20859b6561ddd38632047b12bd

  prebuild-devcontainer:
    uses: nikobockerman/github-workflows/.github/workflows/devcontainer-cache.yaml@227dcb13eb6b8e20859b6561ddd38632047b12bd
    permissions:
      contents: read
      packages: write
    with:
      cache-type: intermediate
  check-devcontainer:
    needs: prebuild-devcontainer
    uses: ./.github/workflows/check-devcontainer.yaml
