name: CI
on:
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-test-run:
    uses: ./.github/workflows/build-test-run.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@a3ff11ed76f5e286d3a5e11ec6f6395ddbe6412d
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@a3ff11ed76f5e286d3a5e11ec6f6395ddbe6412d
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@a3ff11ed76f5e286d3a5e11ec6f6395ddbe6412d
  check-rustfmt:
    uses: ./.github/workflows/check-rustfmt.yaml
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@a3ff11ed76f5e286d3a5e11ec6f6395ddbe6412d

  prebuild-devcontainer:
    uses: nikobockerman/github-workflows/.github/workflows/devcontainer-cache.yaml@a3ff11ed76f5e286d3a5e11ec6f6395ddbe6412d
    permissions:
      contents: read
      packages: write
    with:
      cache-type: intermediate
  check-devcontainer:
    needs: prebuild-devcontainer
    uses: ./.github/workflows/check-devcontainer.yaml
